permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
markdown: rdiscount
paginate: 10
tags_path: /tags.html
tagline: Your bite-sized boardgame bulletin
production_url: http://podcast.board2pieces.com
author :
  name : Ted Alspach
  email : ted@beziergames.com